name: Release CocoQR FE

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.vars.outputs.VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate tag source
        run: |
          echo "Checking tag rules..."

          # Lấy danh sách branch chứa commit này
          BRANCHES=$(git branch -r --contains $GITHUB_SHA)

          echo "Branches: $BRANCHES"

          # Nếu là staging tag (-rc)
          if [[ "${{ github.ref_name }}" == *"-rc"* ]]; then
            echo "Detected STAGING tag"

            echo "$BRANCHES" | grep "origin/dev" > /dev/null
            if [ $? -ne 0 ]; then
              echo "❌ Staging tag must come from dev branch"
              exit 1
            fi
          else
            echo "Detected PRODUCTION tag"

            echo "$BRANCHES" | grep "origin/main" > /dev/null
            if [ $? -ne 0 ]; then
              echo "❌ Production tag must come from main branch"
              exit 1
            fi
          fi

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          if [[ "${{ github.ref_name }}" == *"-rc"* ]]; then
              MODE=staging
            else
              MODE=production
            fi

          docker build \
           --build-arg VITE_MODE=$MODE \
           --build-arg VITE_STAGING_API_URL=${{ vars.VITE_STAGING_API_URL }} \
           --build-arg VITE_PRODUCTION_API_URL=${{ vars.VITE_PRODUCTION_API_URL }} \
           -t ${{ secrets.DOCKER_USERNAME }}/mywallet-fe:${{ steps.vars.outputs.VERSION }} \
           .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mywallet-fe:${{ steps.vars.outputs.VERSION }}

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-rc') }}

  deploy-staging:
    if: contains(github.ref_name, '-rc')
    needs: build
    runs-on: ubuntu-latest
    environment: STAGING

    steps:
      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/mywallet-fe:${{ needs.build.outputs.version }}
            cd /opt/mywallet-fe-staging
            export IMAGE_TAG=${{ needs.build.outputs.version }}
            docker compose up -d mywallet-fe-staging
            docker image prune -f

  deploy-production:
    if: "!contains(github.ref_name, '-rc')"
    needs: [build]
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if RC exists
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          BASE_VERSION=${VERSION%%-*}

          echo "Checking RC for $BASE_VERSION"

          RC_TAGS=$(git tag -l "${BASE_VERSION}-rc*")

          if [ -z "$RC_TAGS" ]; then
            echo "❌ No RC tag found for ${BASE_VERSION}"
            exit 1
          fi

           echo "Found RC tags:"
           echo "$RC_TAGS"
           echo "✅ RC exists. Continue deploying."

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/mywallet-fe:${{ needs.build.outputs.version }}
            cd /opt/mywallet-fe-production
            export IMAGE_TAG=${{ needs.build.outputs.version }}
            docker compose up -d mywallet-fe-production
            docker image prune -f
